spring.application.name=custom-file-convertor-connector
camunda.client.mode=saas
camunda.client.auth.client-id=IBoGeRaD.Uip.PKiOEtotOP1FolpG4RX
camunda.client.auth.client-secret=vmKo0aH.eQA1Z06-1~3aB.g_RrXi8gUoSM9qcbHBAINATISnsXJrddq9S3Iuj0IZ
camunda.client.cloud.cluster-id=0b6b5da4-9aac-459b-baf1-1813f24aaf67
camunda.client.cloud.region=sin-1
spring.main.web-application-type=none